name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACC0l4DlDvboJ06h1Y+478vRM8bxSwGVJAbnVPZxpgIxBQAAAJgm06B6JtOg
egAAAAtzc2gtZWQyNTUxOQAAACC0l4DlDvboJ06h1Y+478vRM8bxSwGVJAbnVPZxpgIxBQ
AAAEB8txT4nBpB1qdhDdiHK4iBVNK9fdsI+kYRJx89KOi9DLSXgOUO9ugnTqHVj7jvy9Ez
xvFLAZUkBudU9nGmAjEFAAAAE2hoamo1NTAxM0BnbWFpbC5jb20BAg==
-----END OPENSSH PRIVATE KEY-----}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
